name: MSYS2 Build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYSTEM: CLANG64
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with: 
          submodules: recursive
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: CLANG64
          update: true
          install: >-
            mingw-w64-clang-x86_64-toolchain
            mingw-w64-clang-x86_64-pkgconf
            mingw-w64-clang-x86_64-gtk4
            autotools
            intltool
            zip
      - name: autogen the sources
        run: ./autogen.sh
      - name: configure the sources
        run: ./configure
      - name: Build the sources
        run: make

      - name: Install
        run: make install